###
POST http://localhost:8080/security/record/addRecord
Content-Type: application/json

{
  "key": "63023941-9cc5-4da4-80ae-4190584fcdd6",
  "content": "ZmQkvLVroM/nsjlY2sH2psanw/U5RRcFYnopQoeeK3T51hPNyFahZCpc7lHTmVm8o/cMuNSsPO412WBkyHj+PvyxbN/pK/DjdTg4z7IXtMNtTkJYZ14KuQwUMZ8kCy31YiQ0+5MlwIWC0HpSQFNwyUbiyAHsxV6pquBN07Surnnpk1jL9GLYEB4yMp626o8tZ3WqECAyRo3nX7Vg41flwzhSJXST4d9dkHFIRNZrxfXrUwKD/tDBJoADGACSxZEWV3I7PA6O0S0BOuK4X+E60nhV1TvIheFDBX7gFoyV3H8gGoIn3jT2BorTZTTBH2FnA51/bGpJ/QvKWjoj6TTCNDqSlFqwoSYUzZzXaXYRNXxMa3ROeBgyd4ZrntUShjbY5Fi7HyAdkGeHsMunz7hnHwud3HPRf1zduTlX20R9BFnTl6F1xns+xpq+6x/+FeIzE1IfYiExbQ18VTC3KyOlJmuuq+g0o0neZ1yQpJsbMdcFDYOI4JuG9CFCMDOzOyE6giVfxAbtBGXQ74VsPgjxzsFuZcxOxyo0zOQA6ztZZ8npHQbMPjfVbIu+Az0wubOaKyf+2o9iDZj9dGolP1TNK4VKiD5AyY0rv2pdsOQ8ZGxQK2za+GnE8xOmUwlLBVkd02ETV066cj2ZhYnndV4lX572PIzk7wBhjFdhZcc99dw="
}

###
POST http://localhost:8080/rsa/encrypt
Content-Type: application/json

{
  "inbounds": [
    {
      "port": 35647,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "bf0cc246-f36c-4a80-bd08-26905a9c1e0b",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/straw"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "outboundTag": "block",
        "protocol": [
          "bittorrent"
        ]
      }
    ]
  }
}
