###
POST http://localhost:8080/security/record/addRecord
Content-Type: application/json

{
  "key": "9a4dc242-de6a-442b-bfcb-a6380c844882",
  "content": "J0ulDHprT7S9nx0bedUab6jpRuSunHY/az8Vu+4ETmagpw2lOw07WqQ6UwC7v5LZs27S6zhPWqCO+mVSwKKm6FXSXIOETWUc9yPRy3d3T1yMXhsOngYWtup9SKTw+o6k1T7uDDffi3N5EH1mJvQFmJnadTLmxUv5fPAQr9ig/ZL1rFHbdy5PPNRyVoqIbW4aom6P2VyVaVCy0oXSmlDbQwx5K91fg3WbvHVTTRvr1lJRbATn1CINb2ZQz/BWrmZEZ/3WccbExI4+iQukxk9nb/Wn/vDLwZIQbgByG3A7i/LOS4iJ24kqRNFPpqEMdumM9+eS3z5zFP7MEnhT+XJBNhJPyehtHRzArS7N/80FmuxmYLcaZZDwVZ0GR92ujq5kCOyMH58/utNtsprjssxIO99V7+0i5+EkLDLvBzGl6xj8BdTq7cSwfzddDC4i4/SDiGxMdyhz5QhQCRqOlXTI0DCUJOoO0Aa7/sItjuHyU2bFQ8mS3XfaimfeCiGqH/Eq2n2CV2MgTp/uHPMbWP8vJ+9qxPSSba6AfOE4w4h3tiYxqyrqJ8kfpn+4BiDBnCnMSu2SkPWRwnehcN2V1/lIKX6O8FjJM1LTcL15OqQxtebYT6XJ8emaLUV4CCB+qOESQjUvvd8YdNykn4AepAuHdh3XR9BPKNzNBcht6zEKLNY="
}

###
POST http://localhost:8080/rsa/encrypt
Content-Type: application/json

{
  "domain": "{{domain}}",
  "subDomain": "{{subDomain}}",
  "recordType": "A",
  "recordLine": "默认",
  "value": "{{value}}",
  "SignatureMethod": "HmacSHA1",
  "Action": "RecordCreate",
  "secretId": "{{secretId}}",
  "secretKey": "{{secretKey}}"
}